var annotated_dup =
[
    [ "ftxui", "namespaceftxui.html", [
      [ "animation", "namespaceftxui_1_1animation.html", [
        [ "Animator", "classftxui_1_1animation_1_1Animator.html", "classftxui_1_1animation_1_1Animator" ],
        [ "Params", "classftxui_1_1animation_1_1Params.html", "classftxui_1_1animation_1_1Params" ]
      ] ],
      [ "box_helper", "namespaceftxui_1_1box__helper.html", [
        [ "Element", "structftxui_1_1box__helper_1_1Element.html", "structftxui_1_1box__helper_1_1Element" ]
      ] ],
      [ "flexbox_helper", "namespaceftxui_1_1flexbox__helper.html", [
        [ "Block", "structftxui_1_1flexbox__helper_1_1Block.html", "structftxui_1_1flexbox__helper_1_1Block" ],
        [ "Global", "structftxui_1_1flexbox__helper_1_1Global.html", "structftxui_1_1flexbox__helper_1_1Global" ],
        [ "Line", "structftxui_1_1flexbox__helper_1_1Line.html", "structftxui_1_1flexbox__helper_1_1Line" ]
      ] ],
      [ "AnimatedColorOption", "group__component.html#structftxui_1_1AnimatedColorOption", "group__component_structftxui_1_1AnimatedColorOption" ],
      [ "AnimatedColorsOption", "structftxui_1_1AnimatedColorsOption.html", "structftxui_1_1AnimatedColorsOption" ],
      [ "AnimationTask", "classftxui_1_1AnimationTask.html", null ],
      [ "AutoReset", "classftxui_1_1AutoReset.html", "classftxui_1_1AutoReset" ],
      [ "Box", "group__screen.html#structftxui_1_1Box", "group__screen_structftxui_1_1Box" ],
      [ "ButtonOption", "group__component.html#structftxui_1_1ButtonOption", "group__component_structftxui_1_1ButtonOption" ],
      [ "Canvas", "group__dom.html#structftxui_1_1Canvas", "group__dom_structftxui_1_1Canvas" ],
      [ "CapturedMouseInterface", "classftxui_1_1CapturedMouseInterface.html", "classftxui_1_1CapturedMouseInterface" ],
      [ "CheckboxOption", "group__component.html#structftxui_1_1CheckboxOption", "group__component_structftxui_1_1CheckboxOption" ],
      [ "Color", "group__screen.html#classftxui_1_1Color", "group__screen_classftxui_1_1Color" ],
      [ "ColorInfo", "group__screen.html#structftxui_1_1ColorInfo", "group__screen_structftxui_1_1ColorInfo" ],
      [ "ComponentBase", "group__component.html#classftxui_1_1ComponentBase", "group__component_classftxui_1_1ComponentBase" ],
      [ "ConstRef", "classftxui_1_1ConstRef.html", "classftxui_1_1ConstRef" ],
      [ "ConstStringListRef", "classftxui_1_1ConstStringListRef.html", "classftxui_1_1ConstStringListRef" ],
      [ "ConstStringRef", "classftxui_1_1ConstStringRef.html", "classftxui_1_1ConstStringRef" ],
      [ "Dimensions", "group__screen.html#structftxui_1_1Dimensions", "group__screen_structftxui_1_1Dimensions" ],
      [ "DropdownOption", "group__component.html#structftxui_1_1DropdownOption", "group__component_structftxui_1_1DropdownOption" ],
      [ "EntryState", "structftxui_1_1EntryState.html", "structftxui_1_1EntryState" ],
      [ "Event", "group__component.html#structftxui_1_1Event", "group__component_structftxui_1_1Event" ],
      [ "FlexboxConfig", "group__dom.html#structftxui_1_1FlexboxConfig", "group__dom_structftxui_1_1FlexboxConfig" ],
      [ "Image", "group__screen.html#classftxui_1_1Image", "group__screen_classftxui_1_1Image" ],
      [ "InputOption", "group__component.html#structftxui_1_1InputOption", "group__component_structftxui_1_1InputOption" ],
      [ "InputState", "structftxui_1_1InputState.html", "structftxui_1_1InputState" ],
      [ "LinearGradient", "group__dom.html#structftxui_1_1LinearGradient", "group__dom_structftxui_1_1LinearGradient" ],
      [ "Loop", "group__component.html#classftxui_1_1Loop", "group__component_classftxui_1_1Loop" ],
      [ "MenuEntryOption", "group__component.html#structftxui_1_1MenuEntryOption", "group__component_structftxui_1_1MenuEntryOption" ],
      [ "MenuOption", "group__component.html#structftxui_1_1MenuOption", "group__component_structftxui_1_1MenuOption" ],
      [ "Mouse", "group__component.html#structftxui_1_1Mouse", "group__component_structftxui_1_1Mouse" ],
      [ "Node", "group__dom.html#classftxui_1_1Node", "group__dom_classftxui_1_1Node" ],
      [ "NodeDecorator", "classftxui_1_1NodeDecorator.html", "classftxui_1_1NodeDecorator" ],
      [ "Pixel", "group__screen.html#structftxui_1_1Pixel", "group__screen_structftxui_1_1Pixel" ],
      [ "RadioboxOption", "group__component.html#structftxui_1_1RadioboxOption", "group__component_structftxui_1_1RadioboxOption" ],
      [ "ReceiverImpl", "classftxui_1_1ReceiverImpl.html", "classftxui_1_1ReceiverImpl" ],
      [ "Ref", "classftxui_1_1Ref.html", "classftxui_1_1Ref" ],
      [ "Requirement", "group__dom.html#structftxui_1_1Requirement", "group__dom_structftxui_1_1Requirement" ],
      [ "ResizableSplitOption", "structftxui_1_1ResizableSplitOption.html", "structftxui_1_1ResizableSplitOption" ],
      [ "Screen", "group__screen.html#classftxui_1_1Screen", "group__screen_classftxui_1_1Screen" ],
      [ "ScreenInteractive", "group__component.html#classftxui_1_1ScreenInteractive", "group__component_classftxui_1_1ScreenInteractive" ],
      [ "Selection", "group__dom.html#classftxui_1_1Selection", "group__dom_classftxui_1_1Selection" ],
      [ "SenderImpl", "classftxui_1_1SenderImpl.html", "classftxui_1_1SenderImpl" ],
      [ "SliderOption", "structftxui_1_1SliderOption.html", "structftxui_1_1SliderOption" ],
      [ "StringRef", "classftxui_1_1StringRef.html", "classftxui_1_1StringRef" ],
      [ "Table", "group__dom.html#classftxui_1_1Table", "group__dom_classftxui_1_1Table" ],
      [ "TableSelection", "classftxui_1_1TableSelection.html", "classftxui_1_1TableSelection" ],
      [ "TerminalInputParser", "classftxui_1_1TerminalInputParser.html", "classftxui_1_1TerminalInputParser" ],
      [ "UnderlineOption", "group__component.html#structftxui_1_1UnderlineOption", "group__component_structftxui_1_1UnderlineOption" ],
      [ "WindowOptions", "structftxui_1_1WindowOptions.html", "structftxui_1_1WindowOptions" ],
      [ "WindowRenderState", "group__component.html#structftxui_1_1WindowRenderState", "group__component_structftxui_1_1WindowRenderState" ]
    ] ]
];