on:
  # On new releases:
  workflow_call:
    inputs:
      tag_name:
        required: true
        type: string

  # On manual trigger:
  workflow_dispatch:
    inputs:
      tag_name:
        required: true
        type: string

jobs:    
  publish:
    uses: bazel-contrib/publish-to-bcr/.github/workflows/publish.yaml@v0.0.4
    with:
      tag_name: ${{ inputs.tag_name }}
      registry_fork: ArthurSonzogni/bazel-central-registry
    permissions:
      attestations: write
      contents: write
      id-token: write
    secrets:
      publish_token: ${{ secrets.PUBLISH_TOKEN }}
