name: "Publish to Bazel Central Registry"

on:
  # Manual kick-off (you type the tag)
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Tag to publish"
        required: true
        type: string

permissions:
  contents:     write

jobs:
  publish:
    uses: bazel-contrib/publish-to-bcr/.github/workflows/publish.yaml@v0.0.4
    with:
      tag_name: ${{ github.event.inputs.tag_name }}
      registry_fork: ArthurSonzogni/bazel-central-registry
      attest: false

    secrets:
      publish_token: ${{ secrets.PUBLISH_TOKEN }}
